### ISSUE TITLE
[Bug]: Build error with vehilce-app-cpp-sdk using libfmt v10.2.1

### ISSUE THREAD

**Issue by RaviprasadBS** [eclipse-velocitas/vehicle-app-cpp-sdk#93]
### Severity

High

### What release version, tag or commit-hash did you use?

v0.5.1

### Current Behavior

Encountered an error when building the vehicle-app-cpp-sdk with libfmt v10.2.1. 
The build succeeds with libfmt v9.1, but fails with v10.0 or later.

The build fails in _GrpcDataPointValueProvider.cpp_ at line 45 :

![image](https://github.com/eclipse-velocitas/vehicle-app-cpp-sdk/assets/171107122/d269fdfb-e983-4f99-a1b7-4ab0fb2efe22)

Following error occurred :

![image](https://github.com/eclipse-velocitas/vehicle-app-cpp-sdk/assets/171107122/4fc35d0d-265d-4f7e-892f-dd54d91bc3e2)

### Steps to Reproduce

1. Clone the eclipse-velocitas/vehicle-app-cpp-sdk repository.
2. Update libfmt to v10.2.1 in the project's dependencies.
3. Attempt to build the vehicle-app-cpp-sdk.

### Expected Behavior

The build should complete successfully, as it does with libfmt v9.1.

### Possible Solution

- Typecast the enum class Failure to its underlying integral type in the logger statement.
- Overload format_as() for the specific enum.
- Typecast the enum using fmt::underlying()

### Additional Information

- The build environment is set up using Yocto.
- The SDK is attempted to be built with a Yocto setup using libfmt v10.2.1.

### Code of Conduct

- [X] I agree to follow this project's "Code of Conduct".

**Comment by MP91** [comment]
fixed with #96
